# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: public

jobs:
# Please do not rename this job
  build-project:
    name: build Personal-Portfolio
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - name: Build Node assets
        env:
          CI: true
          EMAIL_FORWARD: gosalia.krunal@gmail.com
          EMAIL_PASS: b5y!DSgb5}yOG55p
          EMAIL_USER: portfolio@krunalgosalia.com
          IONOS_HOST: smtp.ionos.com
          IONOS_PORT: 465
          PORT: 8000
          REACT_APP_GOOGLE_API_KEY: AIzaSyB1akkt-osFuIYDoAuM5p2J2l2PNdfvQcg
          REACT_APP_WEATHER_APP_API_KEY: 65ae069219d542b5a65212723231011
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm ci
          npm run build
          node server.js

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-us.ionos.space
          project-id: 7e24a958-5a92-4eab-8965-b81d526ab619
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/Personal-Portfolio/config.yaml
          action: upload
